coverage:
  status:
    project:
      default: off
      cli:
        threshold: 1%
      core:
        threshold: 1%
    patch: off

flags:
  core:
    paths:
      - "!testing/"
      - "!cmd/"
  cli:
    paths:
      - "cmd/subee/"
