coverage:
  status:
    project:
      cli:
        threshold: 1%
        paths:
          - "cmd/subee/"
      core:
        threshold: 1%
        paths:
          - "!testing/"
          - "!cmd/"
    patch: off
