// Code generated by github.com/wantedly/subee/cmd/subee. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

