// Code generated by github.com/wantedly/subee/cmd/subee. DO NOT EDIT.

package consumer

import (
	"context"
	"encoding/json"

	"github.com/pkg/errors"
	"github.com/wantedly/subee"

	"your-first-cloudpubsub-app/pkg/model"
)

// NewEventConsumerAdapter created a consumer-adapter instance that converts incoming messages into model.Event.
func NewEventConsumerAdapter(consumer EventConsumer) subee.Consumer {
	return &eventConsumerAdapterImpl{consumer: consumer}
}

type eventConsumerAdapterImpl struct {
	consumer EventConsumer
}

func (a *eventConsumerAdapterImpl) Consume(ctx context.Context, m subee.Message) error {
	var err error
	obj := new(model.Event)
	err = json.Unmarshal(m.Data(), obj)
	if err != nil {
		return errors.WithStack(err)
	}
	err = a.consumer.Consume(ctx, obj)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}
